on : push
jobs :
      first-job:
          runs-on : ubuntu-latest
          steps :
                - run : node --version
                - run : npm --version
                - run : npx eslint index.js --fix
                - uses : actions/checkout@v3
                - run : node index.js